CREATE TYPE user_role AS ENUM (
    'USER',
    'CREATOR',
    'ADMIN'
    );

-- LOCAL is the username/password login kept for admins; the others are the
-- external identity providers the school already runs.
CREATE TYPE auth_provider AS ENUM (
    'LOCAL',
    'ISERV',
    'MOODLE'
    );

CREATE TYPE ticket_status AS ENUM (
    'VALID',
    'USED',
    'CANCELLED'
    );

CREATE TABLE users
(
    user_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_first_name    VARCHAR(100)  NOT NULL,
    user_last_name     VARCHAR(100)  NOT NULL,
    user_email         VARCHAR(255)  NOT NULL,
    user_role          user_role     NOT NULL DEFAULT 'USER',
    user_auth_provider auth_provider NOT NULL DEFAULT 'LOCAL',
    -- The subject the identity provider gives us. NULL for LOCAL accounts.
    user_external_id   VARCHAR(255),
    -- Only ever set for LOCAL accounts. NULL for anyone who signs in via IServ/Moodle,
    -- so an OAuth account can never be taken over with a password.
    user_password_hash VARCHAR(255),
    user_created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Addresses are compared case-insensitively, so uniqueness has to be too.
CREATE UNIQUE INDEX idx_users_email ON users (LOWER(user_email));

-- One account per subject per provider. Partial, so the many LOCAL accounts
-- with a NULL external id do not collide with each other.
CREATE UNIQUE INDEX idx_users_external_identity
    ON users (user_auth_provider, user_external_id)
    WHERE user_external_id IS NOT NULL;

-- orders.order_user_id has pointed at nothing since V0001.
ALTER TABLE orders
    ADD CONSTRAINT orders_order_user_id_fkey
        FOREIGN KEY (order_user_id) REFERENCES users (user_id);

-- The entry window of a ticket type: one product may admit from 18:00, another
-- only from 22:00. NULL on either side means "no limit in that direction".
ALTER TABLE products
    ADD COLUMN product_valid_from  TIMESTAMP,
    ADD COLUMN product_valid_until TIMESTAMP;

ALTER TABLE products
    ADD CONSTRAINT products_valid_window_check
        CHECK (product_valid_from IS NULL
            OR product_valid_until IS NULL
            OR product_valid_from < product_valid_until);

-- One row per admitted person: an order item with quantity 3 produces 3 tickets,
-- because each one is scanned separately at the door.
CREATE TABLE tickets
(
    ticket_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The payload of the QR code. Random and unguessable, so a ticket cannot be
    -- forged by counting up from someone else's.
    ticket_code       VARCHAR(64)   NOT NULL UNIQUE,
    ticket_order_id   INT           NOT NULL,
    ticket_product_id INT           NOT NULL,
    ticket_status     ticket_status NOT NULL DEFAULT 'VALID',
    ticket_issued_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticket_used_at    TIMESTAMP,
    FOREIGN KEY (ticket_order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    FOREIGN KEY (ticket_product_id) REFERENCES products (product_id),
    -- A ticket is used exactly when it carries the time it was scanned.
    CONSTRAINT tickets_used_at_check
        CHECK ((ticket_status = 'USED') = (ticket_used_at IS NOT NULL))
);
CREATE INDEX idx_tickets_order_id ON tickets (ticket_order_id);
CREATE INDEX idx_tickets_product_id ON tickets (ticket_product_id);
