CREATE TABLE users
(
    user_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The id the SSO gives this person. Stable, unlike the email address.
    user_sso_subject VARCHAR(255) NOT NULL UNIQUE,
    user_email       VARCHAR(255) NOT NULL,
    user_first_name  VARCHAR(100) NOT NULL,
    user_last_name   VARCHAR(100) NOT NULL
);

-- Admins do not come from the SSO: they log in on the admin login form.
CREATE TABLE admins
(
    admin_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_username      VARCHAR(100) NOT NULL UNIQUE,
    -- bcrypt hash, never the password itself
    admin_password_hash VARCHAR(100) NOT NULL
);

-- A ticket type, e.g. "Abiball 2027".
CREATE TABLE products
(
    product_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name              VARCHAR(255)   NOT NULL,
    product_description       TEXT,
    product_price             DECIMAL(10, 2) NOT NULL CHECK (product_price >= 0),
    product_location          VARCHAR(255)   NOT NULL,
    product_starts_at         TIMESTAMP      NOT NULL,
    product_max_tickets       INT            NOT NULL CHECK (product_max_tickets >= 0),
    -- Tickets held by pending and paid orders.
    product_allocated_tickets INT            NOT NULL DEFAULT 0 CHECK (product_allocated_tickets >= 0)
);

CREATE TABLE orders
(
    order_id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_user_id        INT         NOT NULL REFERENCES users (user_id),
    order_status         VARCHAR(20) NOT NULL CHECK (order_status IN ('PENDING', 'PAID', 'CANCELLED')),
    order_created_at     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_payment_due_at TIMESTAMP   NOT NULL,
    order_paid_at        TIMESTAMP
);
CREATE INDEX idx_orders_user_id ON orders (order_user_id);

-- One row per person: ordering 3 tickets creates 3 rows, each with its own QR code.
CREATE TABLE tickets
(
    ticket_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The random, unguessable content of the QR code.
    ticket_code       VARCHAR(64)    NOT NULL UNIQUE,
    ticket_order_id   INT            NOT NULL REFERENCES orders (order_id),
    ticket_product_id INT            NOT NULL REFERENCES products (product_id),
    -- The price at order time, so a later price change does not alter old orders.
    ticket_price      DECIMAL(10, 2) NOT NULL
);
CREATE INDEX idx_tickets_order_id ON tickets (ticket_order_id);
