CREATE TYPE order_status AS ENUM (
    'ORDERED',
    'PAYED',
    'DELIVERED',
    'REVOKED',
    'CANCELLED'
    );

CREATE TABLE orders
(
    order_id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_user_id          INT            NOT NULL,
    order_date             TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_total_amount     DECIMAL(10, 2) NOT NULL,
    order_payment_due_date TIMESTAMP      NOT NULL,
    order_payment_date     TIMESTAMP,
    order_status           order_status   NOT NULL
);
CREATE INDEX idx_orders_user_id ON orders (order_user_id);

CREATE TABLE products
(
    product_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name        VARCHAR(255)   NOT NULL,
    product_description TEXT,
    product_price       DECIMAL(10, 2) NOT NULL,
    product_stock       INT            NOT NULL
);

CREATE TABLE order_items
(
    order_item_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_order_id   INT            NOT NULL,
    order_item_product_id INT            NOT NULL,
    order_item_quantity   INT            NOT NULL,
    order_item_price      DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (order_item_order_id) REFERENCES orders (order_id),
    FOREIGN KEY (order_item_product_id) REFERENCES products (product_id)
);
CREATE INDEX idx_order_items_order_id ON order_items (order_item_id);
CREATE INDEX idx_order_items_product_id ON order_items (order_item_product_id);

